### ISSUE TITLE
Too many heap sections

### ISSUE THREAD

**Issue by natuneko** [v-analyzer/v-analyzer#12]
### Describe the bug

I have started v-analyzer and an error appears during indexing.(This occurs when 2/4)
And when you close it, it comes back out again.

### Expected Behavior

The server starts up.

### Current Behavior

I get an error "Too many heap sections" when indexing is 2/4
![image](https://github.com/v-analyzer/v-analyzer/assets/65665072/d0929124-7019-46f0-9a27-7d103315297d)
![image](https://github.com/v-analyzer/v-analyzer/assets/65665072/7620a2e0-98a8-4ed2-a2ce-41aeb79b7390)

### Reproduction Steps

Open V project in vscode

### Environment details (`v doctor` output)

V full version: V 0.4.0 049fa3c.e407579
OS: windows, Microsoft Windows 10 Pro v19045 64 rbg
Processor: 4 cpus, 64bit, little endian,

getwd: C:\Users\natuneko
vexe: C:\Users\natuneko\scoop\apps\v\0.4\v.exe
vexe mtime: 2023-07-01 01:56:24

vroot: OK, value: C:\Users\natuneko\scoop\apps\v\0.4
VMODULES: OK, value: C:\Users\natuneko\.vmodules
VTMP: OK, value: C:\Users\natuneko\AppData\Local\Temp\v_0

Git version: git version 2.41.0.windows.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: Error: exec failed (CreateProcess) with code 2: 指定されたファイルが見つかりません。
 cmd: cc --version
thirdparty/tcc: N/A

### Editor name

vscode

### v-analyzer Version

0.0.1-beta.1

**Comment by i582** [comment]
Hi
Can you attach logs from `~/.config/v-analyzer/logs`?

**Comment by natuneko** [comment]
[v-analyzer.gc.log](https://github.com/v-analyzer/v-analyzer/files/11946443/v-analyzer.gc.log)

**Comment by natuneko** [comment]
Sorry, it was this way!
[v-analyzer.log](https://github.com/v-analyzer/v-analyzer/files/11946523/v-analyzer.log)

**Comment by CKylinMC** [comment]
I got the same error and made a small change to my config to make it works correctly.

I see the logs says:

```
[ERROR] Failed to decode config             err=toml.checker.Checker.check_quoted_escapes escaped Unicode is invalid. Unicode code point...
```

It seems to convert all `/` to `\` from your custom_vroot path but `\` + any letter became a new Unicode character like `\s` for my case and `\N` for @natuneko.

So now fix it should be easy, just use `\\` replace all `/` and then restart the server, it should be OK.
