### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ghostnear** [v-analyzer/v-analyzer#29]
### Describe the bug

A memory leak occurs in the garbage collector?

### Expected Behavior

Everything to work properly.

### Current Behavior

I get a message box saying:

> Fatal error in GC: Too many heap sections.

If I check in task manager I get a memory usage of 4,741.4MB for v-analyzer.exe which is absolutely massive. 

### Reproduction Steps

> Install VSCode extension.
> Use specified version from releases.
> Bug happens.

### Environment details (`v doctor` output)

V full version: V 0.4.0 45e6e7d
OS: windows, Microsoft Windows 11 Pro v22621 64-bit
Processor: 12 cpus, 64bit, little endian,

(everything else is valid, and thus removed from this message as it was unnecessary)

### Editor name

VSCode

### v-analyzer Version

v-analyzer version 0.0.1-beta.1

### VS Code Extension Version

 vscode-v-analyzer-0.0.2

**Comment by ghostnear** [comment]
Forgot to mention this happens when the extension says that it is indexing the V standard library.

**Comment by Ekopalypse** [comment]
Have you checked what has been described in #12 ?

**Comment by ghostnear** [comment]
I did not, but having taken a look now at the config I did not have a custom vroot. Setting one to where the previous root was with the specified fixes seems to work tho.
