### ISSUE TITLE
NeoVim LSP Setup / Config NO_RESULT_CALLBACK_FOUND ...

### ISSUE THREAD

**Issue by JustinStitt** [v-analyzer/v-analyzer#9]
### Describe the bug

When using this config in NeoVim: 

```lua
local configs = require('lspconfig.configs')
local lspconfig = require('lspconfig')
if not configs['v-analyzer'] then
  configs['v-analyzer'] = {
    default_config = {
      cmd = { 'v-analyzer' },
      root_dir = lspconfig.util.root_pattern('.git', '.v-analyzer'),
      filetypes = { 'v', 'vlang' },
    },
  }
end
lspconfig['v-analyzer'].setup {}
```

I am getting this error when editing `.v` files

```
LSP[v-analyzer]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 3,
  jsonrpc = "2.0"
}
```

How are y'all setting up `v-analyzer` in NeoVim/LunarVim?

### Expected Behavior

LSP to work

### Current Behavior

LSP doesn't work as per error message above

### Reproduction Steps

1) Paste config into config.lua or equivalent

2) Open `hello.v` and witness errors upon LSP attachment

### Environment details (`v doctor` output)

`$ v doctor`

```
V full version: V 0.4.0 ab258ae
OS: linux, Ubuntu 22.04.1 LTS (WSL 2) (chroot)
Processor: 6 cpus, 64bit, little endian, Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

getwd: /home/jstitt/playground/vlang
vexe: /home/jstitt/repos/v/v
vexe mtime: 2023-07-03 20:09:28

vroot: OK, value: /home/jstitt/repos/v
VMODULES: OK, value: /home/jstitt/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.27-1-gab258aeb (3 commit(s) behind V master)
.git/config present: true

CC version: cc (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

### Editor name

NeoVim

### v-analyzer Version

v-analyzer version 0.0.1-beta.1

### VS Code Extension Version

N/A

**Comment by shininglove** [comment]
Same issue, I do get autocomplete for standard lib, but none on modules I create. Glad I can somewhat use it still

**Comment by pianocomposer321** [comment]
I'm also getting this error. Does anyone know how to fix it?

**Comment by greidinger-reis** [comment]
sad that it's completely unusable on neovim due to this notification that takes focus out of insert mode and pops up on every key press, if anyone finds a way to supress it please share because it seems that the v-analyzer project is pretty abandoned rn

**Comment by demizer** [comment]
I'm going to attempt to fix this issue.

**Comment by demizer** [comment]
I will at least have a branch, but we need to find a maintainer to merge it if I manage to get a fix working.
